### PR TITLE
adding reference clock to the clocking API

### PR DESCRIPTION
**Pull request by TehWan**
Updated the clocking API to separate the concepts of master clock and reference clock. See #276

### CODE REVIEW

**Comment by TehWan** [comment]
See also https://github.com/JDRadio/SoapyBladeRF/commit/976abcc858f7ed06619f6916d0dc5445fe5053a6 for example implementation.

**Comment by guruofquality** [comment]
BTW I like the set/get/range reference clock addition. Im a little dubious about the new clock sources stuff and deprecating stuff, which has more changes I should make for other projects. The existing clock source API was intended for external references and I think it covers bladerf_set_pll_enable() and related.

I think an additional master clock source API doesnt quite cover bladerf's unique daisy chaining architecture for the master clock; and there is also a corresponding clock output to control as well. I think this is a good place for the read/writeSettings() API until there is an established pattern with a few other devices.

But I would like to include the ref clock API for setReferenceClockRate/getReferenceClockRate/getReferenceClockRates. Can I get the PR for just that change?

**Comment by TehWan** [comment]
> Im a little dubious about the new clock sources stuff and deprecating stuff, which has more changes I should make for other projects. The existing clock source API was intended for external references and I think it covers bladerf_set_pll_enable() and related.

I agree. I think the clock source being set to "external" for any SDR should mean to use an external sync reference, not an external master clock.


> I think this is a good place for the read/writeSettings() API until there is an established pattern with a few other devices.

I also agree. Changing the master clock on demand is not something that seems to be very common, and I am not aware of any useful reasons other than for initial configuration on a modified device. There's always access to the native device handle if more flexibility is necessary.

> But I would like to include the ref clock API for setReferenceClockRate/getReferenceClockRate/getReferenceClockRates. Can I get the PR for just that change?

Sure, I'll get that ready tonight after work.

**Comment by TehWan** [comment]
I've updated the code and made a new PR in #279.

**Pull request closed without merging**
