### PR TITLE
Replaced Travis and Appveyor CI with Github Actions

### PR DESCRIPTION
**Pull request by ncorgan**
Example: https://github.com/pothosware/SoapySDR/actions/runs/1249841541

Note that all failures above are valid and should be fixed after merge.

### CODE REVIEW

**Comment by guruofquality** [comment]
Thats quite the matrix. Since this is building msvc, this PR should delete appveyor.yml

OSX seems to like to fail something in TestConvertTypes, looks fun

The windows back_inserter missing has got to be missing `#include <iterator>`

**Comment by zuckschwerdt** [comment]
> OSX seems to like to fail something in TestConvertTypes, looks fun

Seems like std::sto* cause SIGABRT in [__gnu_cxx::__stoa() bridge call](https://github.com/gcc-mirror/gcc/blob/master/libstdc%2B%2B-v3/include/ext/string_conversions.h#L80), on MacOS gcc only. A bug in gcc's _GLIBCXX11_USE_C99_STDLIB wrappers?

A "fix" is e.g. this ugly thing:
```
    //return std::stod(s);
    char *str_end = nullptr;
    double d = std::strtod(s.c_str(), &str_end);
    if (s == str_end) return true;
    return d;
```

**Comment by ncorgan** [comment]
@guruofquality The commit does remove the Appveyor YAML. I forgot to delete the hook until after this went up. For the fixes, I'd call those separate from the CI merge itself.

**Comment by ncorgan** [comment]
@marcusmueller See https://github.com/pothosware/SoapySDR/pull/325#issuecomment-922469021 above. I assume this will affect GNU Radio's copy as well.

**Comment by ncorgan** [comment]
I have a local branch with what should be fixes for both of these, but I'll wait until this is merged so I'm not pushing broken code.

**Comment by guruofquality** [comment]
> I have a local branch with what should be fixes for both of these, but I'll wait until this is merged so I'm not pushing broken code.

You dont want to push to this branch to see if it makes CI pass?

**Comment by ncorgan** [comment]
Other approach. I trust the compiler errors, so I'd like the use the CI to validate the pull request to prevent a broken trunk. Plus, branch scoping.

**Pull request merged**
