### PR TITLE
Treat MinGW CMake installation paths as Unix instead of MSYS

### PR DESCRIPTION
**Pull request by antoniovazquezblanco**
Based on @Biswa96 review on https://github.com/pothosware/SoapySDR/pull/413, a better fix is proposed.

Sorry about the double PR! :)

### CODE REVIEW

**Comment by antoniovazquezblanco** [comment]
Ping :)

**Comment by guruofquality** [comment]
seems almost like WIN32 doing `set(CMAKE_LIB_DEST cmake)` is just the odd man out and maybe should go away. I dont know if this is still the default search path thing for a visual studio install. Or maybe they should all just be `set(CMAKE_LIB_DEST ${CMAKE_INSTALL_DATADIR}/cmake/${PROJECT_NAME})`

But for now in the spirit of just fixing this for MINGW, should this have been `UNIX OR MSYS OR MINGW`?

**Comment by antoniovazquezblanco** [comment]
@Biswa96, what do you think about @guruofquality  suggestion?

Thanks

**Comment by Biswa96** [comment]
> But for now in the spirit of just fixing this for MINGW, should this have been `UNIX OR MSYS OR MINGW`?

I do not know if this project supports msys or cygwin environment. At least, the above suggestion would not hurt mingw. So, it's ok I guess.

**Comment by antoniovazquezblanco** [comment]
Thank you very much!

**Pull request merged**
